version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: dstubked/circle
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Scan Docker image
          command: docker images
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
