version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: dstubked/circle
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
           name: Get Aqua ScannerCLI
           command: wget -q --user=$AQUA_USER --password=$AQUA_PASSWORD https://download.aquasec.com/scanner/4.6.0/scannercli
      - run:
          name: Check ScannerCLI
          command: ls -la && chmod +x scannercli
      - run:
          name: Scan Docker image
          command: ./scannercli
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
